version: "3"
services:
  server:
    image: nginx
    restart: always
    ports:
      - "8080:80"
    environment:
      NODE_ENV: production
  api:
    image: covid
    restart: always
    ports:
      - "5000:4000"
    environment:
      NODE_ENV: production
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    environment:
      NODE_ENV: production
  database:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "covid_database"
      MYSQL_USER: "domdom58"
      MYSQL_PASSWORD: "domdom58"
      MYSQL_ROOT_PASSWORD: "domdom58"
    expose:
      - "3306"
    volumes:
      - covid_db_volume:/var/lib/mysql
volumes:
  covid_db_volume: